### ISSUE TITLE
基于Hexo的matery主题搭建博客并深度优化 | 悟尘纪

### ISSUE THREAD

**Issue by lxl80** [lxl80/site#12]
https://www.lixl.cn/2019/092856736.html 

 对于有一定技术背景的同学，自己动手搭建博客网站是一个很不错的选择。选择喜欢的主题，按需进行个性化配置，随时在本地用自己喜欢的工具写文章，一键发布到多个博客托管平台，使用自己喜欢的图床/CDN 来加速…

演示站点（悟尘记） 基于 Hexo

**Comment by newjia** [comment]
请教一下，首页的左右滚动板块，如何像你的博客首页一样，做到图片高度缩减之前的一半左右呢?

谢谢了！

**Comment by lxl80** [comment]
> 请教一下，首页的左右滚动板块，如何像你的博客首页一样，做到图片高度缩减之前的一半左右呢?
> 
> 谢谢了！

很抱歉，我不是很明白你的意思。

**Comment by newjia** [comment]
<img width="1415" alt="pic" src="https://user-images.githubusercontent.com/9550458/78702361-0a3ca780-793b-11ea-89c7-ff8db917020b.png">
如图所示，留意到你的首页的轮播卡片，高度并非是主题默认的全屏幕高度。

如果方便，请教一下该高度在哪里可以调整呢，谢谢！

**Comment by newjia** [comment]
自己摸索了一下 把 /themes/matery/layout/_partial/index-cover.ejs 里 53行 的 添加height，
`<div class="carousel carousel-slider center index-cover" data-indicators="true" style="margin-top: -64px; ">`
改为
`<div class="carousel carousel-slider center index-cover" data-indicators="true" style="margin-top: -64px; height: 600px;">`

暂时有效，就是不知道有没有什么问题

**Comment by lxl80** [comment]
理解了，请看一下我的自定义样式： <https://www.lixl.cn/css/my.css> 的 427 行，默认是100%，我调整了。
![image](https://user-images.githubusercontent.com/39109380/78849589-79072700-7a47-11ea-8744-c4a608e2afdc.png)

```css
@media only screen and (min-width: 993px) {
  #articleContent img {
    zoom: 50%;
    max-width: 80%;
    min-width: 60%;
  }

  .index-cover{
    max-height: 70vh;
  }

  .index-card {
    margin-top: -50px;
  }
}
```
